server:
  port: 8989
  servlet:
    context-path: /cmfz_zxx
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz_zxx?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity
